version: '3'

services:
  postgres_test_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DD_TAGS=env:java
    ports:
      - 5445:5432