version: '3'

services:
  postgres_test_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_DB=db
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=password

    ports:
      - 5432:5432